### ISSUE TITLE
Use a specific version tag in docker-compose.yml

### ISSUE THREAD

**Issue by unnawut** [omgnetwork/elixir-omg#1551]
An ODP member reported an issue with pulling our latest code and got an error trying to run through docker-compose:

> I keep getting the following error while trying to spin up the watcher (Ubuntu server 16, in Docker containers)
> ```
> [services.d] starting services
> [services.d] done.
> 2020-05-28 15:00:49.332 [warn] module=OMG.DB.ReleaseTasks.InitKeyValueDB function=process/1 ⋅Creating database at "/app/.omg/data/watcher"⋅
> /app/releases/0.4.3+4445aee/libexec/erts.sh: line 66:   276 Illegal instruction     (core dumped) "$__erl" -boot_var ERTS_LIB_DIR "$RELEASE_ROOT_DIR/lib" -boot "${RELEASE_ROOT_DIR}/bin/start_clean" ${SYS_CONFIG_PATH:+-config "${SYS_CONFIG_PATH}"} -pa "${CONSOLIDATED_DIR}" ${EXTRA_CODE_PATHS:+-pa "${EXTRA_CODE_PATHS}"} "$@"
> [cmd] /watcher_entrypoint exited 132
> ```
> could anyone help me out?

Note the app path containing `0.4.3+4445aee` which means he's still on a very old codebase despite starting the environment from scratch. This is because docker doesn't fetch a tag again if it already has one locally, including `latest` tag.

## Expected behaviour

Pulling the latest codebase and running `docker-compose up -d` should set the user up with the latest docker-compose environment.

The proposal is to replace `latest` tag in `docker-compose.yml` with the up-to-date version tag, same as what we already do in `docker-compose-watcher.yml`

**Comment by kartsims** [comment]
I was actually using `docker-compose-watcher.yml` but checked out `v0.4.8` tag as recommended in the guide (and I see the file has been updated yesterday in `master` branch) I'll try to checkout `master` and keep you updated

**Comment by kartsims** [comment]
I updated to use `v0.4.8` image tag, and am getting a bunch of debug info between the `[services.d] done` and the error, but the error is still there:

```
watcher_1   | [os_mon] memory supervisor port (memsup): Erlang has closed
watcher_1   | [os_mon] cpu supervisor port (cpu_sup): Erlang has closed
watcher_1   | 2020-05-29 20:32:29.513 [warn] module=OMG.DB.ReleaseTasks.InitKeyValueDB function=process/1 ⋅Creating database at "/app/.omg/data/watcher"⋅
watcher_1   | /bin/bash: line 1:   181 Illegal instruction     (core dumped) /app/bin/watcher eval "OMG.DB.ReleaseTasks.InitKeyValueDB.run()"
watcher_1   | [cmd] /watcher_entrypoint exited 132
``` 

Here is my `docker-compose.yml` :

```
version: "2.3"

services:

  postgres:
    image: postgres:9.6.13-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: omisego_dev
      POSTGRES_PASSWORD: omisego_dev
      POSTGRES_DB: omisego_dev
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U omisego_dev
      interval: 5s
      timeout: 3s
      retries: 5

  watcher:
    image: omisego/watcher:v0.4.8
    command: "full_local"
    environment:
      - ETHEREUM_RPC_URL=https://ropsten.infura.io/v3/${INFURA_API_KEY}
      - CHILD_CHAIN_URL=https://childchain.ropsten.v1.omg.network
      - ETHEREUM_NETWORK=ROPSTEN
      - AUTHORITY_ADDRESS=0x3272b97b7f1b74b338cb0fdda167cf76bc4da3b6
      - TXHASH_CONTRACT=0x25e445594f425a7a94141a20b8831580953b92ddd0d12e9c775c571e4f3da08c
      - CONTRACT_ADDRESS_PLASMA_FRAMEWORK=0xa72c9dceeef26c9d103d55c53d411c36f5cdf7ec
      - CONTRACT_ADDRESS_ETH_VAULT=0x2c7533f76567241341d1c27f0f239a20b6115714
      - CONTRACT_ADDRESS_ERC20_VAULT=0x2bed2ff4ee93a208edbf4185c7813103d8c4ab7f
      - CONTRACT_ADDRESS_PAYMENT_EXIT_GAME=0x960ca6b9faa85118ba6badbe0097b1afd8827fac
      - DATABASE_URL=postgres://omisego_dev:omisego_dev@postgres:5432/omisego_dev
      - PORT=7434
      - DD_DISABLED=true
      - DB_PATH=/app/.omg/data
      - ETHEREUM_EVENTS_CHECK_INTERVAL_MS=8000
      - ETHEREUM_STALLED_SYNC_THRESHOLD_MS=300000
      - ETHEREUM_BLOCK_TIME_SECONDS=15
      - EXIT_PROCESSOR_SLA_MARGIN=5520
      - EXIT_PROCESSOR_SLA_MARGIN_FORCED=TRUE
      - LOGGER_BACKEND=console
      - DD_HOSTNAME=datadog
      - APP_ENV=local-development
    ports:
      - "7434:7434"
    healthcheck:
      test: curl watcher:7434
      interval: 5s
      timeout: 3s
      retries: 5
```

I am supposing it has to do with the creation of the `/app/.omg/data/watcher` "database", running a `ls` in the container yields no result:

```
# docker-compose run watcher ls -l /app/.omg/data
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
ls: /app/.omg/data: No such file or directory
[cmd] /watcher_entrypoint exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] syncing disks.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```
