### ISSUE TITLE
Utxo not found when attempting transaction with some utxos

### ISSUE THREAD

**Issue by nicholasmueller** [omgnetwork/elixir-omg#1760]
Some utxos returned from `account.get_utxos` cause `utxo_not_found` error when creating transactions with them. observed on mainnet.

`account.get_utxos` returns these 2 utxos that i want to merge:
```
amount: 10000000000000000
blknum: 83000
creating_txhash: "0x447ec5ec92a647b1d6947c2faf9a575486e5811e4c0576f3d4015722124573b2"
currency: "0xd26114cd6ee289accf82350c8d8487fedb8a0c07"
inserted_at: "2020-06-18T09:40:06Z"
oindex: 1
otype: 1
owner: "0x0339b1187101bce651ee6215c9c9b34b560873c5"
spending_txhash: null
txindex: 0
updated_at: "2020-06-18T09:40:06Z"
utxo_pos: 83000000000001
```

```
amount: 3830922229089327600
blknum: 3692000
creating_txhash: "0xb0bcd3164ef339c63fadbf5e0fbd457470ba8c02ef980e2d5f32617b569cbcaf"
currency: "0xd26114cd6ee289accf82350c8d8487fedb8a0c07"
inserted_at: "2020-10-29T08:06:19Z"
oindex: 0
otype: 1
owner: "0x0339b1187101bce651ee6215c9c9b34b560873c5"
spending_txhash: null
txindex: 0
updated_at: "2020-10-29T08:06:19Z"
utxo_pos: 3692000000000000
```

i create a merge transaction using these 2 utxos and form this typed data:
```
txType:1
input0:
  blknum:83000
  txindex:0
  oindex:1
input1:
  blknum:3692000
  txindex:0
  oindex:0
input2:
  blknum:0
  txindex:0
  oindex:0
input3:
  blknum:0
  txindex:0
  oindex:0
output0:
  outputType:1
  outputGuard:0x0339B1187101bCE651EE6215C9c9b34B560873c5
  currency:0xd26114cd6ee289accf82350c8d8487fedb8a0c07
  amount:3840922229089327700
output1:
  outputType:0
  outputGuard:0x0000000000000000000000000000000000000000
  currency:0x0000000000000000000000000000000000000000
  amount:0
output2:
  outputType:0
  outputGuard:0x0000000000000000000000000000000000000000
  currency:0x0000000000000000000000000000000000000000
  amount: 0
output3:
  outputType: 0
  outputGuard: 0x0000000000000000000000000000000000000000
  currency: 0x0000000000000000000000000000000000000000
  amount: 0
  txData: 0
metadata: 0x0000000000000000000000000000000000000000004d65726765205554584f73
```

I sign and submit the transaction calling `transaction.submit` and get back:
```
code: "submit:utxo_not_found"
description: null
object: "error
```

I suspect the first utxo is the erroneous one. for some reason I cannot spend this utxo.

**Comment by nicholasmueller** [comment]
The suspected erroneous utxo at pos 83000000000001 was already exited:
https://etherscan.io/tx/0xec704671a1ddb5358f6fcf4441d9af5c130dda3f8157dd45f6c066bc9826f915

**Comment by unnawut** [comment]
I can confirm a similar situation for me from the demo.

Running:

```shell
curl -s -X POST https://watcher-info.mainnet.v1.omg.network/account.get_utxos \
-H "Content-Type: application/json" \
-d '{
  "address": "0xf876154263cF61E15e84695096cFdCb5ceEd8D86"
}' \
-w "\n" | jq
```

Gives:
```js
{
  "data": [
    {
      "amount": 1e+16,
      "blknum": 238000,
      "creating_txhash": "0x8150a5c52536df28622ff4b8745a164c05fb7ad60cdc1ce531b77d42ae5ab802",
      "currency": "0xd26114cd6ee289accf82350c8d8487fedb8a0c07",
      "inserted_at": "2020-06-18T10:06:15Z",
      "oindex": 1,
      "otype": 1,
      "owner": "0xf876154263cf61e15e84695096cfdcb5ceed8d86",
      "spending_txhash": null,
      "txindex": 0,
      "updated_at": "2020-06-18T10:06:15Z",
      "utxo_pos": 238000000000001
    },
    {
      "amount": 2146714250335326500,
      "blknum": 239000,
      "creating_txhash": "0xfe89db8a1ae9aa749122cfd85afb0d04fced2bd13068cf21a8d60051ffdd831c",
      "currency": "0xd26114cd6ee289accf82350c8d8487fedb8a0c07",
      "inserted_at": "2020-06-18T10:06:31Z",
      "oindex": 1,
      "otype": 1,
      "owner": "0xf876154263cf61e15e84695096cfdcb5ceed8d86",
      "spending_txhash": null,
      "txindex": 0,
      "updated_at": "2020-06-18T10:06:31Z",
      "utxo_pos": 239000000000001
    },
    ...
    {
      "amount": 2039756824914914600,
      "blknum": 3481000,
      "creating_txhash": "0xad5aa42ecee6ec70d38957619a47b12fc90497c2a20b54c5fe314d446644fd9c",
      "currency": "0xd26114cd6ee289accf82350c8d8487fedb8a0c07",
      "inserted_at": "2020-10-02T11:17:34Z",
      "oindex": 0,
      "otype": 1,
      "owner": "0xf876154263cf61e15e84695096cfdcb5ceed8d86",
      "spending_txhash": null,
      "txindex": 0,
      "updated_at": "2020-10-02T11:17:34Z",
      "utxo_pos": 3481000000000000
    },
    ...
}
```

Running:

```shell
curl -s -X POST https://watcher-info.mainnet.v1.omg.network/account.get_exitable_utxos \
-H "Content-Type: application/json" \
-d '{
  "address": "0xf876154263cF61E15e84695096cFdCb5ceEd8D86"
}' \
-w "\n" | jq
```

Gives: (note that get_exitable_utxos does not return utxo `239000000000001`)

```js
{
  "data": [
    {
      "amount": 1e+16,
      "blknum": 238000,
      "currency": "0xd26114cd6ee289accf82350c8d8487fedb8a0c07",
      "oindex": 1,
      "otype": 1,
      "owner": "0xf876154263cf61e15e84695096cfdcb5ceed8d86",
      "txindex": 0,
      "utxo_pos": 238000000000001
    },
    {
      "amount": 2039756824914914600,
      "blknum": 3481000,
      "currency": "0xd26114cd6ee289accf82350c8d8487fedb8a0c07",
      "oindex": 0,
      "otype": 1,
      "owner": "0xf876154263cf61e15e84695096cfdcb5ceed8d86",
      "txindex": 0,
      "utxo_pos": 3481000000000000
    },
    ...
}
```

Metamask message:

```
Message
  txType: 1
  input0:
    blknum: 239000
    txindex: 0
    oindex: 1
  input1:
    blknum: 0
    txindex: 0
    oindex: 0
  input2:
    blknum: 0
    txindex: 0
    oindex: 0
  input3:
    blknum: 0
    txindex: 0
    oindex: 0
  output0:
    outputType: 1
    outputGuard: 0xf876154263cF61E15e84695096cFdCb5ceEd8D86
    currency: 0xd26114cd6ee289accf82350c8d8487fedb8a0c07
    amount: 1043735294971103340
  output1:
    outputType: 1
    outputGuard: 0xf876154263cF61E15e84695096cFdCb5ceEd8D86
    currency: 0xd26114cd6ee289accf82350c8d8487fedb8a0c07
    amount: 1000000000000000000
  output2:
    outputType: 0
    outputGuard: 0x0000000000000000000000000000000000000000
    currency: 0x0000000000000000000000000000000000000000
    amount: 0
  output3:
    outputType: 0
    outputGuard: 0x0000000000000000000000000000000000000000
    currency: 0x0000000000000000000000000000000000000000
    amount: 0
  txData: 0
  metadata: 0x00000000000000000000
```

The utxo was already exited: https://etherscan.io/tx/0x316e2d1c7be7b25f4e9b8f14f6a64aef008a4cde53d8d971398efa6ce71a6d87
